baseurl: https://reveningstudyhall.netlify.app/
languageCode: en-us
title: R Evening Study Hall
theme: hugo-theme-bootstrap4-blog
paginate: 5
summaryLength: 50
permalinks:
  page: /:slug/
  posts: /:year/:month/:title/
params:
  author: Max Czapanskiy
  date_format: Mon Jan 02, 2006
  description: Tip and tricks learned at R Evening Study Hall
